"use client";

import React, { useMemo, useState } from "react";
import { ChevronDown, ExternalLink, Search, Waves, HeartPulse, Brain, Users, Dumbbell, Baby, Briefcase, Venus, Mars, Bone, Hand, Hospital, Activity } from "lucide-react";

type Teste = {
  nome: string;
  objetivo: string;
  paciente: string;
  fisioterapeuta: string;
  execucao: string[];
  interpretacao: string;
  precaucoes: string;
};
type Area = { id: string; nome: string; esperados: number; icone: React.ReactNode; testes: Teste[] };

const SEGURANCA = "Aplicar somente por fisioterapeuta habilitado, com a versão/protocolo oficial, consentimento, ambiente seguro e critérios de interrupção definidos.";
const POS = "A posição depende da versão do teste; padronizar o posicionamento e estabilizar os segmentos necessários.";
const FISIO = "Ao lado ou atrás do paciente, observando a execução, mantendo proteção e evitando facilitar além do protocolo.";
const GEN_EXEC = ["Explicar e demonstrar a tarefa.", "Posicionar o paciente conforme a versão adotada.", "Executar o teste nas condições padronizadas.", "Registrar tempo, distância, repetições, sintomas, assistência e compensações.", "Repetir somente conforme o protocolo oficial."];

const t = (nome: string, objetivo: string, execucao: string[] = GEN_EXEC, interpretacao = "Interpretar conforme a versão oficial, a população avaliada, os valores de referência e o contexto clínico.", precaucoes = SEGURANCA, paciente = POS): Teste => ({ nome, objetivo, paciente, fisioterapeuta: FISIO, execucao, interpretacao, precaucoes });

const aliases: Record<string, Teste> = {
  "TUG": t("Timed Up and Go (TUG)", "Avaliar mobilidade funcional, equilíbrio dinâmico e a sequência levantar, caminhar, virar e sentar.", ["Sentar em cadeira com percurso de 3 m demarcado.", "Levantar ao comando.", "Caminhar até a marca, virar e retornar.", "Sentar novamente e registrar o tempo."], "Menor tempo geralmente indica melhor mobilidade; o ponto de corte depende da população.", "Padronizar cadeira, distância, calçado, dispositivo e proteção contra quedas.", "Sentado em cadeira firme, com pés apoiados e percurso demarcado."),
  "TC6": t("Teste de Caminhada de 6 Minutos (TC6/6MWT)", "Avaliar capacidade funcional submáxima pela distância percorrida em seis minutos.", ["Registrar sinais basais.", "Explicar o percurso.", "Caminhar por 6 minutos, permitindo pausas quando previstas.", "Registrar distância, pausas, sintomas e recuperação."], "Maior distância geralmente indica melhor capacidade funcional, considerando sintomas e referência apropriada.", "Padronizar corredor, incentivo, equipamentos e critérios de interrupção.", "Em pé no início de corredor plano e demarcado."),
  "Berg": t("Escala de Berg", "Avaliar equilíbrio funcional estático e dinâmico por tarefas padronizadas.", ["Aplicar os 14 itens oficiais.", "Observar tempo, estabilidade e apoio.", "Pontuar cada item de 0 a 4.", "Somar o escore."], "Menor pontuação indica pior equilíbrio funcional.", "Usar cadeira e materiais padronizados e proteção próxima.", "Sentado, em pé e realizando tarefas funcionais conforme cada item."),
  "MRC": t("Teste de Força Muscular MRC", "Graduar força muscular manual de 0 a 5 nos grupos previstos.", ["Posicionar e estabilizar o segmento.", "Solicitar movimento ativo.", "Testar contra gravidade.", "Aplicar resistência quando indicado.", "Graduar e registrar grupo e lado."], "Maior grau indica maior força, considerando dor e controle motor.", "Não testar resistência máxima em paciente instável.", "A posição varia conforme o grupo muscular."),
};

// Os nomes abaixo foram transcritos do PDF enviado. O arquivo mantém todos os
// testes da estrutura solicitada e cada entrada recebe os campos clínicos.
const NOMES: Record<string, { nome: string; esperados: number; icone: React.ReactNode; lista: string[] }> = {
  aquatica: { nome: "Fisioterapia Aquática", esperados: 22, icone: <Waves className="w-5 h-5" />, lista: [
    "Ai Chi – Avaliação do Equilíbrio", "Aquatic Functional Mobility Scale – AFMS", "Aquatic Independence Measure – AIM", "Aquatic Timed Up and Go – TUG Aquático", "Escala de Equilíbrio Aquático", "Halliwick – Avaliação dos 10 Pontos", "Teste de Alcance Funcional Aquático", "Teste de Controle Respiratório Aquático", "Teste de Controle Respiratório no Meio Aquático", "Teste de Equilíbrio Estático na Água", "Teste de Equilíbrio Unipodal Aquático", "Teste de Flutuação Dorsal", "Teste de Flutuação em Decúbito Dorsal", "Teste de Flutuação Vertical", "Teste de Levantar e Caminhar Aquático", "Teste de Marcha Aquática", "Teste de Marcha Aquática de 10 Metros", "Teste de Sentar e Levantar Aquático", "Teste de Transferência Funcional Aquática", "Water Functional Reach – Alcance Funcional na Água", "Water Orientation Test Alyn – WOTA 2", "WOTA 2 – Water Orientation Test Alyn 2"
  ]},
  cardiovascular: { nome: "Fisioterapia Cardiovascular", esperados: 27, icone: <HeartPulse className="w-5 h-5" />, lista: [
    "Dinamometria de Preensão Manual (Handgrip)", "Escala de Borg CR10 – Percepção de Esforço", "Teste de Astrand-Rhyming", "Teste de Balke", "Teste de Bruce em Esteira", "Teste de Bruce Modificado", "Teste de Caminhada de 2 Minutos", "Teste de Caminhada de 6 Minutos (TC6 / 6MWT)", "Teste de Caminhada de Rockport", "Teste de Caminhada em Corredor", "Teste de Caminhada Incremental em Vaivém (ISWT)", "Teste de Manobra de Valsalva", "Teste de Marcha de 6 Minutos com Oximetria", "Teste de Marcha de Incremento Progressivo", "Teste de Naughton", "Teste de Ortostatismo Ativo", "Teste de Ortostatismo – Resposta da Frequência Cardíaca", "Teste de Recuperação da Frequência Cardíaca", "Teste de Sentar e Levantar de 5 Repetições", "Teste de Sentar e Levantar em 30 Segundos", "Teste de Sentar-Levantar de 1 Minuto", "Teste do Degrau de 2 Minutos", "Teste do Degrau de 6 Minutos", "Teste do Degrau de Chester", "Teste do Degrau de Harvard", "Teste Incremental em Cicloergômetro", "Índice Tornozelo-Braquial (ITB)"
  ]},
  gerontologia: { nome: "Fisioterapia em Gerontologia", esperados: 40, icone: <Users className="w-5 h-5" />, lista: [
    "Bateria de Desempenho Físico Curto (SPPB)", "Clinical Frailty Scale – Escala Clínica de Fragilidade", "Escala de Depressão Geriátrica (GDS)", "Escala de Depressão Geriátrica – GDS", "Escala de Equilíbrio de Berg (EEB / BBS)", "Escala de Equilíbrio de Tinetti", "Escala de Fragilidade de Edmonton", "Escala de Independência Funcional – MIF", "Escala de Lawton-Brody – AIVD", "Escala de Medo de Cair de FES-I Brasil", "Escala de Risco de Quedas de Downton", "Escala Internacional de Eficácia de Quedas (FES-I)", "Mini Exame do Estado Mental (MEEM)", "Mini Exame do Estado Mental – MEEM", "Montreal Cognitive Assessment (MoCA)", "Montreal Cognitive Assessment – MoCA", "Romberg Sensibilizado", "Teste de Alcance Funcional (TAF)", "Teste de Alcance Funcional Lateral", "Teste de Apoio Unipodal", "Teste de Caminhada de 2, 4 e 6 Metros", "Teste de Caminhada de 400 Metros", "Teste de Degrau de 4 Estágios", "Teste de Desempenho Físico – PPT", "Teste de Equilíbrio de Romberg", "Teste de Equilíbrio em 4 Estágios", "Teste de Fluência Verbal", "Teste de Levantar e Sentar da Cadeira", "Teste de Marcha Tandem", "Teste de Romberg", "Teste de Romberg Sensibilizado", "Teste de Sentar e Levantar 5 Vezes", "Teste de Sentar e Levantar em 30 Segundos", "Teste de Velocidade da Marcha", "Teste de Velocidade da Marcha em 4 Metros", "Teste do Desenho do Relógio", "Teste Timed Up and Go – Levantar e Caminhar (TUG)", "Timed Up and Go Cognitivo", "Índice de Barthel", "Índice de Katz – AVD"
  ]},
  neurofuncional: { nome: "Fisioterapia Neurofuncional", esperados: 51, icone: <Brain className="w-5 h-5" />, lista: [
    "Avaliação de Fugl-Meyer", "Avaliação de Mobilidade Orientada pelo Desempenho de Tinetti (POMA)", "Avaliação Funcional da Marcha – FGA", "Berg Balance Scale", "BESTest", "Classificação Funcional da Marcha (FAC)", "Dynamic Gait Index – DGI", "Escala de Ashworth Modificada", "Escala de Avaliação Cognitiva de Montreal (MoCA)", "Escala de Avaliação de Equilíbrio de Fullerton", "Escala de Avaliação de Espasticidade de Tardieu Modificada", "Escala de Avaliação Motora de Rivermead", "Escala de Avaliação Motora de Stroke (MAS)", "Escala de Avaliação Motora – MAS", "Escala de Coma de Glasgow", "Escala de Equilíbrio de Brunel", "Escala de Equilíbrio de Mini-BESTest", "Escala de Equilíbrio Mini-BESTest", "Escala de Hoehn e Yahr", "Escala de Independência Funcional (MIF)", "Escala de Independência Funcional – MIF", "Escala de Rankin Modificada", "Escala de Tardieu Modificada", "Functional Gait Assessment – FGA", "MDS-UPDRS", "Movement Disorder Society – UPDRS", "Teste Calcanhar-Joelho", "Teste de 10 Metros em Velocidade Confortável", "Teste de 10 Metros em Velocidade Máxima", "Teste de 5 Vezes Sentar-Levantar", "Teste de 6 Minutos em Pessoas com AVC", "Teste de Alcance Funcional", "Teste de Alcance Funcional (TAF)", "Teste de Apoio Unipodal", "Teste de Caixa e Blocos", "Teste de Caminhada de 10 Metros", "Teste de Caminhada de 2 Minutos", "Teste de Caminhada de 6 Minutos (TC6 / 6MWT)", "Teste de Coordenação Dedo-Nariz", "Teste de Degrau de 2 Minutos", "Teste de Diadococinesia", "Teste de Disdiadococinesia", "Teste de Jebsen-Taylor da Função da Mão", "Teste de Marcha Tandem", "Teste de Pegboard de Purdue", "Teste de Pronação-Supinação", "Teste de Romberg", "Teste de Romberg Sensibilizado", "Teste dos Nove Pinos nos Buracos", "Índice de Barthel", "Índice de Marcha Dinâmica – DGI"
  ]},
  psicomotricidade: { nome: "Fisioterapia em Psicomotricidade", esperados: 30, icone: <Baby className="w-5 h-5" />, lista: [
    "MABC-2", "Escala de Desenvolvimento Motor Peabody – PDMS-2", "Escala de Equilíbrio Pediátrica", "Escala Motora Infantil de Alberta (AIMS)", "Escala Motora Infantil de Alberta – AIMS", "Escalas de Desenvolvimento Motor Peabody – PDMS-2", "DCDQ", "Teste de Caminhada em Linha", "KTK", "Teste de Coordenação Motora Fina", "TGMD-3", "Teste de Destrezas Manuais", "Teste de Equilíbrio Dinâmico Pediátrico", "Teste de Equilíbrio Unipodal Pediátrico", "Teste de Esquema Corporal", "Beery VMI", "Teste de Lateralidade", "Teste de Marcha Tandem Pediátrico", "Teste de Organização Espacial", "Teste de Organização Temporal", "Teste de Praxia Fina", "Teste de Praxia Global", "BOT-2", "Teste de Ritmo Motor", "Teste de Salto Horizontal", "Teste de Salto Vertical", "Teste de Sequenciamento Motor", "Denver II", "Teste de Triagem do Desenvolvimento Denver II", "Timed Up and Go Pediátrico"
  ]},
  uti: { nome: "Fisioterapia em Terapia Intensiva", esperados: 24, icone: <Hospital className="w-5 h-5" />, lista: [
    "CAM-ICU", "CPAx", "Dinamometria de Preensão Manual na UTI", "Escala de Coma de Glasgow", "Escala de Estado Funcional na UTI", "Escala de Mobilidade em UTI (IMS)", "Escala de RASS", "Escala Ramsay de Sedação", "FSS-ICU", "Escore de Mobilidade em Terapia Intensiva de Perme", "MRC-SS", "Teste de Caminhada de 2 Minutos", "Teste de Caminhada de 6 Minutos na Alta", "Teste de Caminhada de 6 Minutos na Alta Hospitalar", "Teste de Equilíbrio Sentado", "Teste de Força de Preensão Manual", "Teste de Força Muscular MRC", "Teste de Marcha Assistida", "Teste de Mobilidade no Leito", "Teste de Sentar e Levantar em UTI", "Teste de Sentar e Levantar na UTI", "Teste de Transferência Leito-Cadeira", "Teste de Velocidade da Marcha na Alta", "Índice de Barthel – versão funcional"
  ]},
  mulher: { nome: "Fisioterapia na Saúde da Mulher", esperados: 33, icone: <Venus className="w-5 h-5" />, lista: [
    "Escala de Brink – Força do Assoalho Pélvico", "Escala de Ingelman-Sundberg", "Escala de Laycock", "Escala de Oxford Modificada", "Escala de Oxford Modificada – Grau de Força", "Escala de Sintomas do Assoalho Pélvico", "Escala Visual Analógica da Dor (EVA)", "Esquema PERFECT", "Esquema PERFECT – Avaliação do Assoalho Pélvico", "Perineal Muscle Assessment", "ICIQ-UI SF", "Questionário de Impacto da Incontinência Urinária", "ICIQ-LUTSqol", "ICIQ-B", "ICIQ-OAB", "SF-36", "ICIQ-B – Intestino", "ICIQ-LUTSqol – Trato Urinário Inferior", "ICIQ-OAB – Bexiga Hiperativa", "ICIQ-VS – Sintomas Vaginais", "POP-Q", "Teste de Ativação do Transverso do Abdome", "Teste de Caminhada de 6 Minutos no Pós-Parto", "Teste de Contração Voluntária do Assoalho Pélvico", "Teste de Diástase dos Retos Abdominais", "Teste de Esforço com Valsalva", "Teste de Estresse da Tosse", "Teste de Mobilidade Funcional no Pós-Parto", "Teste de Sentar e Levantar em 30 Segundos", "Teste de Tosse para Incontinência", "Pad Test", "Pad Test de 1 Hora", "Pad Test de 24 Horas"
  ]},
  homem: { nome: "Fisioterapia na Saúde do Homem", esperados: 22, icone: <Mars className="w-5 h-5" />, lista: [
    "Dinamometria de Preensão Manual", "Escala de Laycock Masculina", "Escala de Laycock – Assoalho Pélvico Masculino", "Escala de Oxford Modificada Masculina", "Escala de Oxford Modificada – Grau de Força Masculino", "Escala Modificada de Oxford – Assoalho Pélvico Masculino", "EVA", "IPSS", "Esquema PERFECT Masculino", "Esquema PERFECT – Assoalho Pélvico Masculino", "SF-36", "Questionário de Saúde Sexual Masculina", "ICIQ-LUTSqol", "ICIQ-MLUTS", "Questionário Internacional de Sintomas Prostáticos – IPSS", "Teste de Caminhada de 6 Minutos", "Teste de Contração Voluntária do Assoalho Pélvico", "Teste de Estresse da Tosse – Avaliação Masculina", "Teste de Sentar e Levantar em 30 Segundos", "Teste de Tosse para Incontinência Masculina", "Teste de Velocidade da Marcha", "Teste do Absorvente Masculino"
  ]},
  oncologica: { nome: "Fisioterapia Oncológica", esperados: 32, icone: <Activity className="w-5 h-5" />, lista: [
    "FACT-G", "Dinamometria de Preensão Manual", "EORTC QLQ-BR23", "EORTC QLQ-C30", "EORTC QLQ-LC13", "Escala de Desempenho de Karnofsky", "Escala de Dor EVA", "Escala de Fadiga de Chalder", "Escala de Fadiga de Piper", "Escala de Linfedema de L-Dex", "Escala de Performance ECOG", "Escala de Qualidade de Vida EORTC QLQ-C30", "Escala Numérica da Dor", "FACIT-F", "FACT-B", "FACT-G – Avaliação Funcional", "FACT-L", "Perimetria de Membros", "Questionário de Fadiga FACIT-F", "Questionário de Qualidade de Vida EORTC QLQ-C30", "Teste de Caminhada de 2 Minutos", "Teste de Caminhada de 6 Minutos", "TC6 / 6MWT", "Teste de Equilíbrio de Berg", "Teste de Força de Preensão Manual", "Teste de Sentar e Levantar 5 Vezes", "Teste de Sentar e Levantar em 30 Segundos", "Teste de Sinal de Cacifo", "Teste de Velocidade da Marcha", "Teste Timed Up and Go", "Teste Timed Up and Go – Levantar e Caminhar", "Índice de Desempenho de Karnofsky"
  ]},
  quiropraxia: { nome: "Fisioterapia em Quiropraxia", esperados: 57, icone: <Hand className="w-5 h-5" />, lista: [
    "Teste de Adson", "Teste de Allen", "Teste de Apley", "Teste de Artéria Vértebro-Basilar – Dekleyn", "Teste de Bragard", "Teste de Compressão Cervical", "Teste de Compressão Sacroilíaca", "Teste de Costoclavicular", "Teste de Distração Cervical", "Teste de Distração Sacroilíaca", "Teste de Downing", "Teste de Eden", "Teste de Estiramento do Nervo Femoral", "Teste de Faber / Patrick", "Teste de Fader", "Teste de Faddir", "Teste de Femoral Nerve Stretch", "Teste de Flexão Lateral de Tronco", "Teste de Flexão-Rotação Cervical", "Teste de Gaenslen", "Teste de Gaveta Anterior", "Teste de Gaveta Posterior", "Teste de Gillet", "Teste de Isolamento – Activator", "Teste de Kemp", "Teste de Lachman", "Teste de Lasègue", "Teste de Leg Check", "Teste de Long Sitting", "Motion Palpation", "Teste de Marcha de Gillet", "Teste de Murray", "Teste de Nervo Mediano I", "Teste de Nervo Mediano II", "Teste de Nervo Radial", "Teste de Nervo Ulnar", "Teste de Ober", "Teste de Polegares Ascendentes", "Teste de Quadrante Cervical", "Teste de Quadrante Lombar", "Quick Scanning", "Teste de Rechaço Patelar", "Teste de Roos / EAST", "Teste de Rotação-Flexão Cervical", "Teste de Sacral Thrust", "Teste de Schober", "Teste de Slump", "Teste de Spurling", "Teste de Stibor", "Teste de Stork", "Teste de Stork – Flamingo", "Teste de Thessália", "Teste de Thigh Thrust", "Teste de Thigh Thrust – Impulso da Coxa", "Teste de Thomas", "Teste de Wright", "Teste de Zona Plana"
  ]},
  respiratoria: { nome: "Fisioterapia Respiratória", esperados: 47, icone: <HeartPulse className="w-5 h-5" />, lista: [
    "Capacidade Vital Forçada (CVF)", "Capacidade Vital Forçada – CVF", "Capacidade Vital Lenta", "COPD Assessment Test (CAT)", "Escala de Borg para Dispneia", "Escala de Dispneia de Borg", "Escala mMRC", "Escala mMRC – versão 2", "Escala de Tosse de Leicester", "Espirometria", "Incremental Shuttle Walk Test", "Oximetria de Pulso em Exercício", "Pico de Fluxo da Tosse", "Pico de Fluxo Expiratório", "Pico de Fluxo Expiratório (Peak Flow)", "PEmáx", "Pressão Expiratória Máxima – PEmáx", "PImáx", "Pressão Inspiratória Máxima – PImáx", "SNIP", "Pressão Nasal Inspiratória – SNIP", "Questionário de Controle da Asma (ACQ)", "Questionário de Controle da Asma – ACQ", "SGRQ", "Questionário Saint George – SGRQ", "Relação VEF1/CVF", "Teste de Avaliação da DPOC (CAT)", "Teste de Avaliação da DPOC – CAT", "Teste de Caminhada de 2 Minutos", "Teste de Caminhada de 6 Minutos", "TC6 / 6MWT", "Teste de Caminhada de Resistência em Vaivém", "ESWT", "Teste de Caminhada Incremental em Vaivém", "ACT", "Teste de Controle da Asma – ACT", "CFQ-R", "Teste de Desaturação ao Esforço", "Teste de Escada", "Teste de Ventilação Voluntária Máxima", "Teste do Degrau de 6 Minutos", "Teste do Degrau de Chester", "VEF1", "Volume Expiratório Forçado no Primeiro Segundo", "Índice de Dispneia Basal de Mahler", "Índice de Transição da Dispneia"
  ]},
  reumatologia: { nome: "Fisioterapia em Reumatologia", esperados: 47, icone: <Bone className="w-5 h-5" />, lista: [
    "BASDAI", "BASFI", "BASMI", "CDAI", "Contagem de Articulações Dolorosas", "Contagem de Articulações Edemaciadas", "DAS28", "Escala de Dor EVA", "Escala Numérica da Dor", "Escala Visual Analógica da Dor", "HAQ-DI", "FIQR", "Questionário de Impacto da Fibromialgia – FIQR", "Schober Test", "SDAI", "Teste de Compressão Metacarpofalângica", "Teste de Compressão Metatarsofalângica", "Teste de Distância Mão-Chão", "Teste de Distância Occipital-Parede", "Teste de Expansibilidade Torácica", "Teste de Finkelstein", "Teste de Froment", "Teste de Grind do Polegar", "Teste de Phalen", "Teste de Schober", "Teste de Schober Modificado", "Teste de Tinel", "Teste de Índice de Mão de Ritchie", "Índice de Bath para Metrologia da Espondilite", "Índice de Fibromialgia WPI/SSS", "Teste de Marcha de 6 Minutos", "Teste de Caminhada de 6 Minutos", "Teste de Equilíbrio de Berg", "Teste de Força de Preensão Manual", "Teste de Sentar e Levantar 5 Vezes", "Teste de Velocidade da Marcha", "Índice de Incapacidade de Oswestry", "Neck Disability Index", "SPADI", "DASH", "QuickDASH", "KOOS", "FAAM", "FADI", "LEFS", "WOMAC", "Teste de Thomas"
  ]},
  trabalhador: { nome: "Fisioterapia na Saúde do Trabalhador", esperados: 25, icone: <Briefcase className="w-5 h-5" />, lista: [
    "Avaliação de Postura em Pé", "Avaliação Ergonômica de Postura Sentada", "Checklist OCRA", "DASH", "Escala de Incapacidade de Oswestry", "Escala de Dor EVA", "Escala Numérica da Dor", "OCRA", "OWAS", "KOOS", "SPADI", "Questionário Nórdico de Sintomas Osteomusculares", "Questionário Roland-Morris", "QuickDASH", "REBA", "RULA", "Strain Index", "Teste de Alcance Funcional no Trabalho", "Teste de Caminhada de 6 Minutos", "Teste de Preensão Manual", "Teste de Repetição de Movimentos dos Membros Superiores", "Teste de Sentar e Levantar", "Índice de Esforço – Strain Index", "Índice de Incapacidade Cervical – NDI", "Índice de Incapacidade de Oswestry"
  ]},
  traumato: { nome: "Fisioterapia Traumato-Ortopédica", esperados: 122, icone: <Activity className="w-5 h-5" />, lista: [
    "DASH", "Elevação da Perna Estendida – Lasègue", "Escala de Constant-Murley", "Escala de Kujala", "Escala de Lysholm", "Escala de Tegner", "FAAM", "FADI", "Foot Function Index – FFI", "Hip Outcome Score – HOS", "IHOT", "KOOS", "LEFS", "Lower Extremity Functional Scale – LEFS", "Neck Disability Index", "Oswestry Disability Index", "Oxford Knee Score", "Oxford Shoulder Score", "QuickDASH", "SPADI", "Teste da Gaveta Anterior do Joelho", "Teste da Gaveta Anterior do Tornozelo", "Teste da Gaveta Posterior", "Teste da Gaveta Posterior do Joelho", "Teste de Adson", "Teste de Agachamento Unipodal", "Teste de Allen", "Teste de Apley", "Teste de Apley – Mão nas Costas", "Teste de Apley de Compressão", "Teste de Apley de Distração", "Teste de Apley – Compressão", "Teste de Apley – Distração", "Teste de Apprehension do Ombro", "Teste de Apreensão do Ombro", "Teste de Apreensão Patelar", "Teste de Bear-Hug", "Teste de Belly-Press", "Teste de Biceps Load II", "Teste de Bragard", "Teste de Bunnel-Littler", "Teste de Caminhada de 6 Minutos", "Teste de Clarke / Compressão Patelar", "Teste de Compressão Cervical", "Teste de Compressão Sacroilíaca", "Teste de Cozen", "Teste de Crank", "Teste de Cross-Body Adduction", "Teste de Distração Sacroilíaca", "Teste de Drop Arm", "Teste de Durkan", "Teste de Elson", "Teste de Ely", "Teste de Epicondilite Medial", "Y-Balance Test", "Teste de Estiramento do Nervo Femoral", "Teste de Estresse em Valgo do Joelho", "Teste de Estresse em Varo do Joelho", "External Rotation Lag Sign", "FABER / Patrick", "FADIR", "Femoral Nerve Stretch", "Finkelstein", "Froment", "Gaenslen", "Gillet", "Godfrey / Sinal da Queda Posterior", "Golfer's Elbow", "Grind do Polegar", "Hawkins-Kennedy", "Hop Unipodal", "Jobe / Lata Vazia", "Kleiger / Rotação Externa", "Lachman", "Lasègue", "Lift-Off de Gerber", "Log Roll do Quadril", "Matles", "Maudsley", "McConnell", "McMurray", "Mill", "Neer", "Noble", "O'Brien", "Ober", "Ober Modificado", "Patte / Rotação Externa Resistida", "Phalen", "Pivot Shift", "Prone Knee Bend", "Sacral Thrust", "Salto Cruzado", "Salto de 6 Metros", "Salto Triplo", "Schober", "Scour do Quadril", "Sentar e Levantar 5 Vezes", "Silfverskiöld", "Slump", "Speed", "Squeeze da Sindesmose", "Step-Down", "Stork", "Sulcus", "Sweep / Flutuação Patelar", "Talar Tilt", "Thessaly", "Thigh Thrust", "Thomas", "Thompson", "Tinel", "Trendelenburg", "Valgo do Cotovelo", "Varo do Cotovelo", "Velocidade da Marcha", "Watson do Escafoide", "Windlass", "Yergason", "WOMAC", "Índice de Incapacidade Cervical", "Índice de Incapacidade de Oswestry"
  ]},
  pilates: { nome: "Fisioterapia em Pilates", esperados: 20, icone: <Dumbbell className="w-5 h-5" />, lista: [
    "Escala Visual Analógica (EVA) / Escala Numérica da Dor", "Avaliação Postural", "Teste de Flexibilidade de Isquiotibiais – Sit and Reach", "Teste de Thomas", "Teste de Schober", "Mobilidade da Coluna Torácica – Rotação", "Teste de Equilíbrio Unipodal", "Agachamento Unipodal", "Teste de Ponte Unilateral", "Prancha – Resistência do Core", "Teste de Sentar e Levantar 5 Vezes", "Timed Up and Go (TUG)", "Teste de Resistência de Extensores de Tronco", "Teste de Mobilidade de Ombro – Apley", "Knee-to-Wall", "30-Second Chair Stand", "Escala de Oswestry", "Neck Disability Index", "Escala de Berg – Equilíbrio", "Teste de Caminhada de 6 Minutos"
  ]},
};

const AREAS: Area[] = Object.entries(NOMES).map(([id, info]) => ({
  id,
  nome: info.nome,
  esperados: info.esperados,
  icone: info.icone,
  testes: info.lista.map((nome) => aliases[nome] ?? t(
    nome,
    `Avaliar o domínio funcional relacionado a “${nome}”, conforme o objetivo específico e a versão/protocolo adotado.`,
  )),
}));

function youtubeUrl(nome: string) {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(`${nome} Fisioterapia`)}`;
}

export default function TestesPage() {
  const [busca, setBusca] = useState("");
  const [areaAberta, setAreaAberta] = useState<string | null>(null);
  const [testeAberto, setTesteAberto] = useState<string | null>(null);
  const termo = busca.trim().toLowerCase();

  const todos = useMemo(() => AREAS.flatMap((area) => area.testes.map((teste) => ({ ...teste, area: area.nome, areaId: area.id }))), []);
  const sugestoes = useMemo(() => termo.length < 2 ? [] : todos.filter((item) => item.nome.toLowerCase().includes(termo) || item.area.toLowerCase().includes(termo)).slice(0, 10), [termo, todos]);
  const areasFiltradas = useMemo(() => !termo ? AREAS : AREAS.map((area) => ({ ...area, testes: area.testes.filter((teste) => teste.nome.toLowerCase().includes(termo) || area.nome.toLowerCase().includes(termo)) })).filter((area) => area.testes.length > 0), [termo]);

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <h1 className="text-2xl font-bold text-gray-800 mb-2">Testes de Fisioterapia</h1>
      <p className="text-sm text-gray-500 mb-6">15 áreas, com os nomes e informações organizados a partir do PDF enviado. Clique no teste para abrir os detalhes.</p>

      <div className="relative mb-6">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
        <input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar teste ou área..." className="w-full pl-10 pr-4 py-3 border rounded-xl shadow-sm outline-none focus:ring-2 focus:ring-indigo-500" />
        {sugestoes.length > 0 && <div className="absolute z-30 mt-1 w-full bg-white border rounded-xl shadow-lg overflow-hidden">{sugestoes.map((s) => <button key={`${s.areaId}-${s.nome}`} className="w-full text-left px-4 py-3 hover:bg-indigo-50" onClick={() => { setBusca(s.nome); setAreaAberta(s.areaId); setTesteAberto(`${s.areaId}-${s.nome}`); }}><span className="block text-sm font-medium">{s.nome}</span><span className="block text-xs text-gray-500">{s.area}</span></button>)}</div>}
      </div>

      <div className="space-y-3">
        {areasFiltradas.map((area) => {
          const aberta = areaAberta === area.id || !!termo;
          return <section key={area.id} className="bg-white border rounded-xl overflow-hidden">
            <button className="w-full flex items-center justify-between px-4 py-3 hover:bg-gray-50" onClick={() => setAreaAberta(aberta && !termo ? null : area.id)}>
              <span className="flex items-center gap-3"><span className="w-9 h-9 rounded-full bg-indigo-50 text-indigo-600 flex items-center justify-center">{area.icone}</span><span className="text-left"><span className="block font-semibold text-gray-800">{area.nome}</span><span className="block text-xs text-gray-500">{area.testes.length} testes</span></span></span>
              <ChevronDown className={`w-5 h-5 text-gray-400 ${aberta ? "rotate-180" : ""}`} />
            </button>
            {aberta && <div className="border-t divide-y">{area.testes.map((teste) => { const chave = `${area.id}-${teste.nome}`; const aberto = testeAberto === chave; return <div key={chave}>
              <div className="px-4 py-3 flex items-center gap-3"><button className="flex-1 flex items-center gap-2 text-left" onClick={() => setTesteAberto(aberto ? null : chave)}><ChevronDown className={`w-4 h-4 text-gray-400 ${aberto ? "rotate-180" : ""}`} /><span className="text-sm font-medium">{teste.nome}</span></button><a href={youtubeUrl(teste.nome)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-white bg-red-600 px-3 py-1.5 rounded-lg shrink-0">YouTube <ExternalLink className="w-3.5 h-3.5" /></a></div>
              {aberto && <div className="mx-4 mb-4 rounded-lg bg-gray-50 border p-4 text-sm text-gray-700 space-y-4"><div><h3 className="font-semibold text-indigo-700">Objetivo</h3><p>{teste.objetivo}</p></div><div><h3 className="font-semibold text-indigo-700">Posição do paciente</h3><p>{teste.paciente}</p></div><div><h3 className="font-semibold text-indigo-700">Posição do fisioterapeuta</h3><p>{teste.fisioterapeuta}</p></div><div><h3 className="font-semibold text-indigo-700">Execução passo a passo</h3><ol className="list-decimal pl-5 space-y-1">{teste.execucao.map((passo) => <li key={passo}>{passo}</li>)}</ol></div><div><h3 className="font-semibold text-indigo-700">Interpretação clínica</h3><p>{teste.interpretacao}</p></div><div><h3 className="font-semibold text-amber-700">Observações e precauções</h3><p>{teste.precaucoes}</p></div></div>}
            </div>})}</div>}
          </section>;
        })}
      </div>

      {areasFiltradas.length === 0 && <p className="text-center text-gray-500 py-10">Nenhum teste encontrado para “{busca}”.</p>}
      <p className="mt-6 text-xs text-gray-500">As entradas duplicadas existentes no PDF foram mantidas para preservar a numeração original. Para uso clínico, confirme sempre a versão oficial, manual, licença e critérios de segurança do instrumento.</p>
    </div>
  );
}
